import Head from "next/head";
import About from "../components/About";
import Landing from "../components/Landing";
import Navbar from "../components/Navbar";
import Services from "../components/Services";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Art Of Body</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Landing />
      <About />
      <Services />
    </div>
  );
}
